export const imageConfigItems = [
  {
    id: 1,
    path: "../images/Alberschwende - Stacked.jpg",
    title: "Alberschwende - Stacked",
    dateTaken: "November 27th, 2021",
    comment:
      "In late November, I took a trip up to Alberschwende in Bregenzerwald to scout out some nice blue hour photos. The snow was coming down more heavily than I expected, making many opportunities challenging, as visibility, then, only minutes before catching the bus down to the valley, I encountered this amazing street just begging for shot. At this particular moment the snow was lighter than it had been and I was able to shoot not only the street, but the cozy farmhouses on the hills in the distance.",
    attribution: "The Author",
  },
  {
    id: 2,
    path: "../images/Bürgenstock I.jpg",
    title: "Bürgenstock I",
    dateTaken: "November 15th, 2019",
    comment:
      "In November of 2019, I was gifted a one night stay at the Bürgenstock Resort with my girlfriend from a good friend and colleague.",
    attribution: "The Author",
  },
  {
    id: 3,
    path: "../images/Christmas Eve in Pitztal, at Dusk.jpg",
    title: "Christmas Eve in Pitztal, at Dusk",
    dateTaken: "December 24th, 2019",
    comment:
      "Weather was less than optimal this Christmas Eve. It was rather warm which was creating a foggy haze among the fields - even up to 4000ft and higher. I set a long delay and captured this emotional picture with a few last minute travelers heading home for the holiday.",
    attribution: "The Author",
  },
  {
    id: 4,
    path: "../images/Feldkirch and the Blizzard of 2021.jpg",
    title: "Feldkirch and the Blizzard of 2021",
    dateTaken: "January 18th, 2021",
    comment:
      "After nearly a week of continual snowing, the Rhine valley saw some of the most snow at the valley level it had seen in years. I got up around 6AM and walked up to a street with a good view in Feldkirch, capturing this show in the blue hour of dawn.",
    attribution: "The Author",
  },
  {
    id: 5,
    path: "../images/Gargellen III.jpg",
    title: "Gargellen III",
    dateTaken: "March 19th, 2021",
    comment:
      "The third and final picture in the Gargellen series, this one is my favorite. A quite and cozy farmhouse still shaking off the feeling of winter, hoping for spring..",
    attribution: "The Author",
  },
  {
    id: 6,
    path: "../images/Last of Dusk at the End of the Rhine Valley.jpg",
    title: "Last of Dusk at the End of the Rhine Valley",
    dateTaken: "December 9th, 2019",
    comment:
      "One of my earlier shots with my Nikon D3500. This sunset was quite a surprise, and led to this incomparable sunset and colors.",
    attribution: "The Author",
  },
  {
    id: 7,
    path: "../images/Sonnwendfeier I.jpg",
    title: "Sonnwendfeier I",
    dateTaken: "June 20th, 2021",
    comment:
      "On June 20th in Austria the summer solstice is celebrated. This is when mountain guides and even locals - head up to the summits of peaks at dusk to lay torches to symbolize the sun staying out all night. On this longest day, there is only about 6 hours of true darkness.",
    attribution: "The Author",
  },
  {
    id: 8,
    path: "../images/Sonnwendfeier II.jpg",
    title: "Sonnwendfeier II",
    dateTaken: "June 20th, 2021",
    comment: "Second shot from the Sonnwendfeier series.",
    attribution: "The Author",
  },
  {
    id: 9,
    path: "../images/Sonnwendfeier III.jpg",
    title: "Sonnwendfeier III",
    dateTaken: "June 20th, 2021",
    comment: "Third shot from the Sonnwendfeier series.",
    attribution: "The Author",
  },
  {
    id: 10,
    path: "../images/Sonnwendfeier IV.jpg",
    title: "Sonnwendfeier IV",
    dateTaken: "June 20th, 2021",
    comment: "Fourth shot from the Sonnwendfeier series.",
    attribution: "The Author",
  },
  {
    id: 11,
    path: "../images/Sonnwendfeier V.jpg",
    title: "Sonnwendfeier V",
    dateTaken: "June 20th, 2021",
    comment: "Fifth shot from the Sonnwendfeier series.",
    attribution: "The Author",
  },
  {
    id: 12,
    path: "../images/Spät Unterwegs in Bartholomäberg.jpg",
    title: "Spät Unterwegs in Bartholomäberg",
    dateTaken: "February 22nd, 2020",
    comment: "Taken in Bartholomäberg just after a fresh snowfall.",
    attribution: "The Author",
  },
  {
    id: 13,
    path: "../images/Gargellen II.jpg",
    title: "Gargellen II",
    dateTaken: "March 19th, 2021",
    comment: "The second in the Gargellen series.",
    attribution: "The Author",
  },
  {
    id: 14,
    path: "../images/Gargellen I.jpg",
    title: "Gargellen I",
    dateTaken: "March 19th, 2021",
    comment:
      "In March of 2021, there was some fresh snowfall in the Montafon valley. After work I headed in, hoping to get a few shots of what might have been the last for winter. Even on this day following the snowfall, it was already quite warm and the snow was very wet.",
    attribution: "The Author",
  },
  {
    id: 15,
    path: "../images/Union - Dome.jpg",
    title: "Union - Dome",
    dateTaken: "December 19th, 2020",
    comment:
      "In mid December 2020, I was in upstate New York for the holidays. A storm and COLD weather brought these fantastic pictures. I couldn't have been on campus for more than 45 minutes - operating the camera, which I had to do without gloves, led to very cold hands.",
    attribution: "The Author",
  },
  {
    id: 16,
    path: "../images/Union - Houses at Dusk.jpg",
    title: "Union - Houses at Dusk",
    dateTaken: "December 19th, 2020",
    comment:
      "Another shot from the Union visit, capturing a bit of the sunset glow in the high, cold, and frozen cirrus clouds.",
    attribution: "The Author",
  },
  {
    id: 17,
    path: "../images/THE ESTATE.jpg",
    title: "THE ESTATE",
    dateTaken: "November 27th, 2020",
    comment:
      "The day after Thanksgiving - and another shot from the United States. A massive estate all lit up for blue hour at Smith Mountain Lake.",
    attribution: "The Author",
  },
  {
    id: 18,
    path: "../images/Tisis at Blue Hour.jpg",
    title: "Tisis at Blue Hour",
    dateTaken: "October 17th, 2020",
    comment: "A wide panorama from above Tisis at blue hour.",
    attribution: "The Author",
  },
  {
    id: 19,
    path: "../images/A Streak in the Night.jpg",
    title: "A Streak in the Night",
    dateTaken: "June 9th, 2020",
    comment:
      "I remember this June night particularly - a cold snap had covered Austria. While it was unfortunate that it was so cold in june, the crisp air left the sky clear and clean.",
    attribution: "The Author",
  },
  {
    id: 20,
    path: "../images/Frastanz Unter Den Drei Schwestern - Dämmerung.jpg",
    title: "Frastanz Unter Den Drei Schwestern - Dämmerung",
    dateTaken: "May 22th, 2020",
    comment:
      "Across from the river Ill, there is a nice field with great views of Frastanz. I thought it would be aesthetic to align the church right in the center of the picture, with the Drei Schwestern looming in the distance.",
    attribution: "The Author",
  },
  {
    id: 21,
    path: "../images/Speeding Home to Feldkirch.jpg",
    title: "Speeding Home to Feldkirch",
    dateTaken: "April 25th, 2020",
    comment:
      "A biker leaves his trail of red light - heading home to Feldkirch.",
    attribution: "The Author",
  },
  {
    id: 22,
    path: "../images/Rhineblick at Blue Hour.jpg",
    title: "Rhineblick at Blue Hour",
    dateTaken: "April 13th, 2020",
    comment: "A shot from the Rhineblick at blue hour.",
    attribution: "The Author",
  },
  {
    id: 23,
    path: "../images/Fog Rolling Out.jpg",
    title: "Fog Rolling Out",
    dateTaken: "February 22th, 2020",
    comment:
      "The day after Thanksgiving - and another shot from the United States. A massive estate all lit up for blue hour at Smith Mountain Lake.",
    attribution: "The Author",
  },
  {
    id: 24,
    path: "../images/Snow Wars.jpg",
    title: "Snow Wars",
    dateTaken: "February 9th, 2020",
    comment:
      'This shot is titled "Snow Wars" due to the endless diligence of the snow makers and stewards of the Montafon Valley who get immediately to work as soon as the days finish at 16:30. Their snow cats and machines light up the mountains as they work.',
    attribution: "The Author",
  },
  {
    id: 25,
    path: "../images/Feldkirch - City of Lights.jpg",
    title: "Feldkirch - City of Lights",
    dateTaken: "January 11th, 2020",
    comment: "A large panorama of Feldkirch in a golden light.",
    attribution: "The Author",
  },
  {
    id: 26,
    path: "../images/Die Werkstatt.jpg",
    title: "Die Werkstatt",
    dateTaken: "December 24th, 2019",
    comment:
      "Another Christmas Eve shot - someone left the light on in the garage, leaving to an emotional arrangement at blue hour.",
    attribution: "The Author",
  },
  {
    id: 27,
    path: "../images/Nordkette Over Innsbruck.jpg",
    title: "Nordkette Over Innsbruck",
    dateTaken: "December 20th, 2019",
    comment: "A sweeping shot of Innsbruck from the Chapel to the Nordkette.",
    attribution: "The Author",
  },
  {
    id: 28,
    path: "../images/The Capital at Blue Hour.jpg",
    title: "The Capital at Blue Hour",
    dateTaken: "November 26th, 2019",
    comment: "The United States Capital at Blue Hour.",
    attribution: "The Author",
  },
  {
    id: 29,
    path: "../images/Bezau at Dusk I.jpg",
    title: "Bezau at Dusk I",
    dateTaken: "December 11th, 2020",
    comment: "Bezau at Dusk I.",
    attribution: "The Author",
  },
  {
    id: 30,
    path: "../images/Bezau at Dusk II.jpg",
    title: "Bezau at Dusk II",
    dateTaken: "December 11th, 2020",
    comment: "Bezau at Dusk II.",
    attribution: "The Author",
  },
  {
    id: 31,
    path: "../images/Bezau at Night I.jpg",
    title: "Bezau at Night I",
    dateTaken: "December 11th, 2020",
    comment: "Bezau at Night I.",
    attribution: "The Author",
  },
  {
    id: 32,
    path: "../images/Bezau at Night II.jpg",
    title: "Bezau at Night II",
    dateTaken: "December 11th, 2020",
    comment: "Bezau at Night II.",
    attribution: "The Author",
  },
  {
    id: 33,
    path: "../images/Bezau at Night III.jpg",
    title: "Bezau at Night III",
    dateTaken: "December 11th, 2020",
    comment: "Bezau at Night III.",
    attribution: "The Author",
  },
  {
    id: 34,
    path: "../images/Hittisau - Evening's Rest.tif",
    title: "Hittisau - Evening's Rest",
    dateTaken: "January 22th, 2020",
    comment:
      "As the sun settled far beyond the mountains, the temperature sank. But bright lights, good friends, and a glowing hearth are more than enough to keep warm during these months where the northern hemisphere tilts away from the sun.",
    attribution: "The Author",
  },
  {
    id: 35,
    path: "../images/Feldkirch - The Foundry.TIF",
    title: "Feldkirch - The Foundry",
    dateTaken: "November 21st, 2021",
    comment:
      "",
    attribution: "The Author",
  },
  {
    id: 36,
    path: "../images/GHOST BUS.TIF",
    title: "GHOST BUS",
    dateTaken: "March 6th, 2022",
    comment:
      "",
    attribution: "The Author",
  },
  {
    id: 37,
    path: "../images/PURPLE HAZE.TIF",
    title: "PURPLE HAZE",
    dateTaken: "March 6th, 2022",
    comment:
      "",
    attribution: "The Author",
  },
  {
    id: 38,
    path: "../images/WITHERING HEIGHTS.TIF",
    title: "WITHERING HEIGHTS",
    dateTaken: "October 12th, 2022",
    comment:
      "",
    attribution: "The Author",
  },
  {
    id: 38,
    path: "../images/NIGHT RIDER I.TIF",
    title: "NIGHT RIDER I",
    dateTaken: "October 12th, 2022",
    comment:
      "The first of what promises to be a series of night shots including my trekking bike.",
    attribution: "The Author",
  },
]
